name: Release

on:
    release:
        types: [created]
jobs:
    build:
        name: Build and Release Go Binary
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos: [linux, windows]
                goarch: [386, amd64, arm]
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: 1.21

            - name: Build Go Binary
              run: |
                export GOOS=${{ matrix.goos }}
                export GOARCH=${{ matrix.goarch }}
                go build -v -o simple_wiki-${{ matrix.goos }}-${{ matrix.goarch }}

            - name: Upload Release Asset
              uses: AButler/upload-release-assets@v3.0
              with:
                files: "./simple_wiki-${{ matrix.goos }}-${{ matrix.goarch }}"
                repo-token: ${{ secrets.GITHUB_TOKEN }}